-- Tables
CREATE OR REPLACE TABLE USER_DB_JACKAL.RAW.STOCK_DATA_LAB (
    SYMBOL VARCHAR NOT NULL,
    DATE TIMESTAMP_NTZ(9) NOT NULL,
    OPEN FLOAT,
    CLOSE FLOAT,
    LOW FLOAT,
    HIGH FLOAT,
    VOLUME NUMBER,
    PRIMARY KEY (SYMBOL, DATE)
);

CREATE OR REPLACE TABLE USER_DB_JACKAL.ANALYTICS.FINAL_PRICE (
    SYMBOL VARCHAR NOT NULL,
    DATE TIMESTAMP_NTZ(9) NOT NULL,
    ACTUAL_CLOSING_PRICE FLOAT,
    FORECASTED_CLOSING_PRICE FLOAT,
    LOWER_BOUND FLOAT,
    UPPER_BOUND FLOAT,
    PRIMARY KEY (SYMBOL, DATE)
);

CREATE OR REPLACE TABLE USER_DB_JACKAL.ADHOC.STOCK_DATA_FORECAST (
    SYMBOL VARCHAR NOT NULL,
    DATE TIMESTAMP_NTZ(9) NOT NULL,
    FORECAST FLOAT,
    LOWER_BOUND FLOAT,
    UPPER_BOUND FLOAT,
    PRIMARY KEY (SYMBOL, DATE)
);

-- View 
CREATE OR REPLACE VIEW USER_DB_JACKAL.ADHOC.STOCK_DATA_VIEW AS
SELECT
    DATE,
    CLOSE,
    SYMBOL
FROM USER_DB_JACKAL.RAW.STOCK_DATA_LAB;

-- Forecast model
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST USER_DB_JACKAL.ANALYTICS.PREDICT_STOCK_PRICE (
    INPUT_DATA         => SYSTEM$REFERENCE('VIEW', 'USER_DB_JACKAL.ADHOC.STOCK_DATA_VIEW'),
    SERIES_COLNAME     => 'SYMBOL',
    TIMESTAMP_COLNAME  => 'DATE',
    TARGET_COLNAME     => 'CLOSE',
    CONFIG_OBJECT      => { 'ON_ERROR': 'SKIP' }
);
